name: Build My Angular App

on:
 push:
  branches: [ main ]
jobs:
 build=angular-app:
  runs-on: ubuntu-latest

  steps: 
    - uses: actions/checkout@v6-beta
    - name: Step Node Js
      uses: actions/setup-node@v6.0.0
      with:
       node-version: 22.x
    - name: Install Dependies
      run: npm install
    - name: Build Angular
      run: npm run build
      
    
  
